---
# file: tasks/users_privileges.yml

- name: "{{ postgresql_daemon }} | Update the user privileges"
  become: True
  become_user: "{{ postgresql_admin_user }}"
  postgresql_user:
    name: "{{ item.name }}"
    db: "{{ item.db | default(omit) }}"
    port: "{{ postgresql_port }}"
    priv: "{{ item.priv | default(omit) }}"
    state: present
    login_host: "{{ item.host | default(omit) }}"
    login_user: "{{ postgresql_admin_user }}"
    login_unix_socket: "{{ postgresql_unix_socket_directories[0] }}"
    role_attr_flags: "{{ item.role_attr_flags | default(omit) }}"
  loop: "{{ postgresql_user_privileges }}"
  when: postgresql_users | length > 0

...
